language: node_js
node_js:
  - node

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(-\S*)?$/

cache:
  yarn: true
  directories:
    - node_modules

install: yarn --frozen-lockfile

before_deploy:
  - npm config set _auth $ARTIFACTORY_API_KEY
  - npm config set email $ARTIFACTORY_EMAIL

deploy:
  provider: script
  script: npm publish
  on:
    branch: master
    tags: true
